EmojidexAndroidLibrary/src/main/java/com/emojidex/emojidexandroid/EmojiDownloader.java, EmojidexAndroidLibrary/src/main/java/com/emojidex/emojidexandroid/PathUtils.java
If emoji download failed, re-download emoji when next time.
=> Downloader

EmojidexAndroid/src/main/java/com/emojidex/emojidexandroid/EmojidexIME.java
=> Debug enter key

EmojidexAndroid/src/main/java/com/emojidex/emojidexandroid/EmojidexIME.java
=> Debug ime.

EmojidexAndroid/src/main/java/com/emojidex/emojidexandroid/MainActivity.java, EmojidexAndroid/src/main/java/com/emojidex/emojidexandroid/SaveDataManager.java, EmojidexAndroid/src/main/res/layout/activity_main.xml, EmojidexAndroid/src/main/res/menu/main.xml, EmojidexAndroid/src/main/res/values-ja/strings.xml, EmojidexAndroid/src/main/res/values/strings.xml
=> Option menu

EmojidexAndroid/src/main/java/com/emojidex/emojidexandroid/EmojidexIME.java, EmojidexAndroid/src/main/java/com/emojidex/emojidexandroid/MainActivity.java
=> Debug clear search result.

EmojidexAndroid/src/main/AndroidManifest.xml
=> Ime auto show

EmojidexAndroid/src/main/java/com/emojidex/emojidexandroid/EmojidexIME.java
=> Debug EmojidexIME::changeCategory.

EmojidexAndroid/src/main/java/com/emojidex/emojidexandroid/MainActivity.java, EmojidexAndroid/src/main/res/values-ja/strings.xml, EmojidexAndroid/src/main/res/values/strings.xml
Check ime enable when boot ime.
=> Check ime enable when boot ime.

EmojidexAndroid/src/main/java/com/emojidex/emojidexandroid/MainActivity.java, EmojidexAndroidLibrary/src/main/java/com/emojidex/emojidexandroid/TextConverter.java
=> Modify convert

.idea/gradle.xml, EmojidexAndroid/src/main/java/com/emojidex/emojidexandroid/EmojidexIME.java, EmojidexAndroid/src/main/java/com/emojidex/emojidexandroid/EmojidexKeyboardView.java, EmojidexAndroid/src/main/java/com/emojidex/emojidexandroid/EmojidexUpdater.java, EmojidexAndroid/src/main/java/com/emojidex/emojidexandroid/MainActivity.java, EmojidexAndroidLibrary/src/main/java/com/emojidex/emojidexandroid/EmojiDownloader.java
=> Use THREAD_POOR_EXECUTOR in downloader.

EmojidexAndroid/src/main/java/com/emojidex/emojidexandroid/MainActivity.java, EmojidexAndroid/src/main/java/com/emojidex/emojidexandroid/SearchActivity.java, EmojidexAndroid/src/main/java/com/emojidex/emojidexandroid/SendSealActivity.java, EmojidexAndroid/src/main/res/values-ja/strings.xml, EmojidexAndroid/src/main/res/values/strings.xml, EmojidexAndroidLibrary/src/main/java/com/emojidex/emojidexandroid/JsonParam.java
=> Debug seal

EmojidexAndroid/src/main/java/com/emojidex/emojidexandroid/EmojidexKeyboardView.java
=> Hide variants scroll right arrow when cannot scroll.

EmojidexAndroidLibrary/src/main/java/com/emojidex/emojidexandroid/PathUtils.java
Use https when download emoji images.
=> Use https when download emoji images.

EmojidexAndroid/src/main/java/com/emojidex/emojidexandroid/MainActivity.java, EmojidexAndroid/src/main/java/com/emojidex/emojidexandroid/SettingsActivity.java, EmojidexAndroid/src/main/res/values-ja/arrays.xml, EmojidexAndroid/src/main/res/values-ja/strings.xml, EmojidexAndroid/src/main/res/values/arrays.xml, EmojidexAndroid/src/main/res/values/strings.xml, EmojidexAndroid/src/main/res/xml/preferences.xml
Implements change text size from preference.
=> Implements change text size from preference.

EmojidexAndroid/src/main/java/com/emojidex/emojidexandroid/EmojidexIME.java
Debug when change no emoji category.
=> Debug when change no emoji category.

EmojidexAndroid/src/main/java/com/emojidex/emojidexandroid/CatalogActivity.java
Auto load index when sealkit scroll last.
=> Auto load index when seelkit scroll last.

EmojidexAndroidLibrary/src/main/AndroidManifest.xml, EmojidexAndroidLibrary/src/main/res/values/strings.xml
=> Debug strings.xml.

EmojidexAndroid/src/main/java/com/emojidex/emojidexandroid/EmojidexKeyboardView.java
Debug PopupWindow layout for android API22～.
=> Debug PopupWindow layout for android API22～.

EmojidexAndroidLibrary/build.gradle, EmojidexAndroidLibrary/src/main/java/com/emojidex/emojidexandroid/DownloadConfig.java, EmojidexAndroidLibrary/src/main/java/com/emojidex/emojidexandroid/EmojiDownloader.java, EmojidexAndroidLibrary/src/main/java/com/emojidex/emojidexandroid/EmojidexFileUtils.java
Download image archive when first time.
=> Download tar.xz file when first time.

EmojidexAndroid/src/main/java/com/emojidex/emojidexandroid/EmojidexIME.java, EmojidexAndroid/src/main/java/com/emojidex/emojidexandroid/EmojidexUpdater.java, EmojidexAndroidLibrary/src/main/java/com/emojidex/emojidexandroid/DownloadListener.java, EmojidexAndroidLibrary/src/main/java/com/emojidex/emojidexandroid/EmojiDownloader.java, EmojidexAndroidLibrary/src/main/java/com/emojidex/emojidexandroid/ImageLoader.java, build.gradle
Update libemojidex library and debug EmojiDownloader.
=> Debug downloader

EmojidexAndroid/build.gradle, EmojidexAndroid/src/main/java/com/emojidex/emojidexandroid/EmojidexKeyboardView.java, EmojidexAndroid/src/main/java/com/emojidex/emojidexandroid/SealGenerator.java, EmojidexAndroidLibrary/build.gradle, EmojidexAndroidLibrary/src/main/java/com/emojidex/emojidexandroid/EmojiDownloader.java, EmojidexAndroidLibrary/src/main/java/com/emojidex/emojidexandroid/Emojidex.java, EmojidexAndroidLibrary/src/main/java/com/emojidex/emojidexandroid/EmojidexFileUtils.java, EmojidexAndroidLibrary/src/main/java/com/emojidex/emojidexandroid/VersionManager.java
Replace underscore to half-width space.
=> Replace underscore

EmojidexAndroid/build.gradle, EmojidexAndroid/src/main/java/com/emojidex/emojidexandroid/EmojidexKeyboardView.java, EmojidexAndroid/src/main/java/com/emojidex/emojidexandroid/MainActivity.java, EmojidexAndroid/src/main/java/com/emojidex/emojidexandroid/SealGenerator.java, EmojidexAndroidLibrary/build.gradle, EmojidexAndroidLibrary/src/main/java/com/emojidex/emojidexandroid/EmojiDownloader.java, EmojidexAndroidLibrary/src/main/java/com/emojidex/emojidexandroid/Emojidex.java, EmojidexAndroidLibrary/src/main/java/com/emojidex/emojidexandroid/EmojidexFileUtils.java, EmojidexAndroidLibrary/src/main/java/com/emojidex/emojidexandroid/VersionManager.java
Auto deEmojify before emojify.
=> Auto de emojify

EmojidexAndroid/build.gradle, EmojidexAndroid/src/main/java/com/emojidex/emojidexandroid/MainActivity.java, EmojidexAndroid/src/main/java/com/emojidex/emojidexandroid/WebViewActivity.java, EmojidexAndroid/src/main/res/layout/activity_webview.xml
=> Use WebView and remove xwalk.

EmojidexAndroid/src/main/java/com/emojidex/emojidexandroid/MainActivity.java, EmojidexAndroidLibrary/src/main/java/com/emojidex/emojidexandroid/EmojidexAnimationDrawable.java
Debug animation emoji frame size when change text size.
=> Debug animation

EmojidexAndroid/src/main/res/values/strings.xml
Change default text size.(small -> medium)
=> Change default text size.

EmojidexAndroid/src/main/java/com/emojidex/emojidexandroid/EmojidexUpdater.java, EmojidexAndroidLibrary/build.gradle, EmojidexAndroidLibrary/src/main/java/com/emojidex/emojidexandroid/Emoji.java, EmojidexAndroidLibrary/src/main/java/com/emojidex/emojidexandroid/EmojiManager.java, EmojidexAndroidLibrary/src/main/java/com/emojidex/emojidexandroid/Emojidex.java, EmojidexAndroidLibrary/src/main/java/com/emojidex/emojidexandroid/VersionManager.java
=> Debug update

EmojidexAndroid/src/main/java/com/emojidex/emojidexandroid/CatalogActivity.java, EmojidexAndroid/src/main/java/com/emojidex/emojidexandroid/EmojidexIME.java, EmojidexAndroid/src/main/java/com/emojidex/emojidexandroid/comparator/ScoreComparator.java
=> Sort index by score.

EmojidexAndroid/src/main/java/com/emojidex/emojidexandroid/CatalogActivity.java, EmojidexAndroid/src/main/java/com/emojidex/emojidexandroid/CatalogAdapter.java, EmojidexAndroid/src/main/java/com/emojidex/emojidexandroid/EmojidexIME.java, EmojidexAndroid/src/main/java/com/emojidex/emojidexandroid/EmojidexIndexUpdater.java, EmojidexAndroid/src/main/java/com/emojidex/emojidexandroid/SearchActivity.java, EmojidexAndroid/src/main/java/com/emojidex/emojidexandroid/UserData.java, EmojidexAndroidLibrary/src/main/java/com/emojidex/emojidexandroid/Emojidex.java, EmojidexAndroidLibrary/src/main/java/com/emojidex/emojidexandroid/EmojidexUser.java, EmojidexAndroidLibrary/src/main/java/com/emojidex/emojidexandroid/TextConverter.java, EmojidexAndroidLibrary/src/main/java/com/emojidex/emojidexandroid/downloader/AbstractJsonDownloadTask.java, EmojidexAndroidLibrary/src/main/java/com/emojidex/emojidexandroid/downloader/EmojiJsonDownloadTask.java, EmojidexAndroidLibrary/src/main/java/com/emojidex/emojidexandroid/downloader/ExtendedJsonDownloadTask.java, EmojidexAndroidLibrary/src/main/java/com/emojidex/emojidexandroid/downloader/IndexJsonDownloadTask.java, EmojidexAndroidLibrary/src/main/java/com/emojidex/emojidexandroid/downloader/SearchJsonDownloadTask.java, EmojidexAndroidLibrary/src/main/java/com/emojidex/emojidexandroid/downloader/UTFJsonDownloadTask.java, EmojidexAndroidLibrary/src/main/java/com/emojidex/emojidexandroid/downloader/arguments/AbstractJsonDownloadArguments.java
Implements animation emoji in sealkit.
=> Animation sealkit

EmojidexAndroid/src/main/java/com/emojidex/emojidexandroid/MainActivity.java
ログアウト時、設定画面からエディタに戻ってきた時、ログアウトできてないことがあったので修正
=> fix logout (fix behavior when login)

EmojidexAndroid/src/main/java/com/emojidex/emojidexandroid/HistoryManager.java
=> Debug upload user history.

EmojidexAndroid/build.gradle, EmojidexAndroid/src/main/java/com/emojidex/emojidexandroid/UserData.java
Remind login when restart application.
=> Update libconceal version.

EmojidexAndroid/src/main/java/com/emojidex/emojidexandroid/EmojidexIME.java, EmojidexAndroid/src/main/java/com/emojidex/emojidexandroid/KeyboardViewManager.java, EmojidexAndroid/src/main/java/com/emojidex/emojidexandroid/SettingsActivity.java, EmojidexAndroid/src/main/res/values-ja/strings.xml, EmojidexAndroid/src/main/res/values/strings.xml, EmojidexAndroid/src/main/res/xml/preferences.xml, EmojidexAndroidLibrary/src/main/java/com/emojidex/emojidexandroid/Emoji.java
- 設定画面に[Standard emoji only]オプションを追加
- オンの時、標準絵文字のみキーボードに表示される
=> Standard only

EmojidexAndroid/src/main/java/com/emojidex/emojidexandroid/MainActivity.java
ログイン直後、プレミアムユーザーでも広告が表示されていたので修正
=> fix ads visibility after login

EmojidexAndroid/src/main/AndroidManifest.xml, EmojidexAndroid/src/main/java/com/emojidex/emojidexandroid/SearchActivity.java
Change SearchActivity launch mode to "singleTop".
=> Change SearchActivity launch mode.

EmojidexAndroid/src/main/AndroidManifest.xml
=> Debug sealkit.

EmojidexAndroidLibrary/src/main/java/com/emojidex/emojidexandroid/downloader/ImageDownloadTask.java
Implements timeout when download emoji image.
=> Implements timeout when download emoji image.

EmojidexAndroid/src/main/java/com/emojidex/emojidexandroid/CatalogActivity.java
Add null check when change category.
=> Add null check when change category.

EmojidexAndroidLibrary/src/main/java/com/emojidex/emojidexandroid/EmojidexLocale.java, EmojidexAndroidLibrary/src/main/java/com/emojidex/emojidexandroid/downloader/ExtendedJsonDownloadTask.java, EmojidexAndroidLibrary/src/main/java/com/emojidex/emojidexandroid/downloader/UTFJsonDownloadTask.java, EmojidexAndroidLibrary/src/main/java/com/emojidex/emojidexandroid/downloader/arguments/ExtendedDownloadArguments.java, EmojidexAndroidLibrary/src/main/java/com/emojidex/emojidexandroid/downloader/arguments/UTFDownloadArguments.java
Use userEmoji API when logined premium or pro user.
=> Debug created at

EmojidexAndroid/src/main/java/com/emojidex/emojidexandroid/SealGenerator.java, EmojidexAndroidLibrary/src/main/java/com/emojidex/emojidexandroid/Emojidex.java, EmojidexAndroidLibrary/src/main/java/com/emojidex/emojidexandroid/EmojidexFileUtils.java
Debug send seal for android 7.
=> Debug send seal

EmojidexAndroidLibrary/src/main/java/com/emojidex/emojidexandroid/Emoji.java, EmojidexAndroidLibrary/src/main/java/com/emojidex/emojidexandroid/TextConverter.java
=> Debug EmojidexAndroidLibrary.

EmojidexAndroid/src/main/AndroidManifest.xml, EmojidexAndroid/src/main/java/com/emojidex/emojidexandroid/CatalogActivity.java, EmojidexAndroid/src/main/java/com/emojidex/emojidexandroid/EmojidexIME.java, EmojidexAndroid/src/main/java/com/emojidex/emojidexandroid/EmojidexMyEmojiUpdater.java, EmojidexAndroid/src/main/java/com/emojidex/emojidexandroid/MainActivity.java, EmojidexAndroid/src/main/java/com/emojidex/emojidexandroid/SaveDataManager.java, EmojidexAndroid/src/main/res/drawable/ic_input_black_24dp.xml, EmojidexAndroid/src/main/res/drawable/ic_search_black_24dp.xml, EmojidexAndroid/src/main/res/layout/activity_catalog.xml, EmojidexAndroid/src/main/res/layout/ime.xml, EmojidexAndroid/src/main/res/values-ja/strings.xml, EmojidexAndroid/src/main/res/values/strings.xml, EmojidexAndroidLibrary/src/main/java/com/emojidex/emojidexandroid/downloader/EmojiDownloader.java, EmojidexAndroidLibrary/src/main/java/com/emojidex/emojidexandroid/downloader/MyEmojiJsonDownloadTask.java, EmojidexAndroidLibrary/src/main/java/com/emojidex/emojidexandroid/downloader/TaskManager.java, EmojidexAndroidLibrary/src/main/java/com/emojidex/emojidexandroid/downloader/TaskType.java, EmojidexAndroidLibrary/src/main/java/com/emojidex/emojidexandroid/downloader/arguments/MyEmojiDownloadArguments.java
=> キーボードとシールキットに「my emoji」を追加

EmojidexAndroid/src/main/java/com/emojidex/emojidexandroid/CatalogActivity.java, EmojidexAndroid/src/main/java/com/emojidex/emojidexandroid/EmojidexIndexUpdater.java, EmojidexAndroid/src/main/java/com/emojidex/emojidexandroid/FilterActivity.java, EmojidexAndroid/src/main/res/drawable/ic_filter_list_black_24dp.xml, EmojidexAndroid/src/main/res/layout/activity_catalog.xml
- シールキットにフィルタリング機能追加
- シールキット１ページあたりの表示絵文字数（limit）の修正
=> Add sort to sealkit

EmojidexAndroidLibrary/src/main/java/com/emojidex/emojidexandroid/EmojiManager.java
=> Debug save json.

EmojidexAndroidLibrary/src/main/java/com/emojidex/emojidexandroid/animation/updater/TextViewAnimationUpdater.java
Debug animation support for TextView.
=> Debug animation support.

EmojidexAndroid/src/main/java/com/emojidex/emojidexandroid/CatalogActivity.java, EmojidexAndroid/src/main/java/com/emojidex/emojidexandroid/MainActivity.java, EmojidexAndroid/src/main/res/drawable/button_white.xml, EmojidexAndroid/src/main/res/drawable/ic_person_left_black_24dp.xml, EmojidexAndroid/src/main/res/drawable/ic_person_right_black_24dp.xml, EmojidexAndroid/src/main/res/layout/activity_catalog.xml, EmojidexAndroid/src/main/res/layout/activity_main.xml, EmojidexAndroid/src/main/res/values-ja/strings.xml, EmojidexAndroid/src/main/res/values/strings.xml
- フォロー／フォロワーボタン追加、該当するemojidexページをブラウザで開く
- エディタ画面上部のMyEmojiボタン削除（キーボード内でMyEmojiを表示するようにしたため）
- ログアウトした時のメニュー表示にバグがあったので修正
=> add following/followers button

EmojidexAndroid/src/main/java/com/emojidex/emojidexandroid/CatalogActivity.java, EmojidexAndroid/src/main/java/com/emojidex/emojidexandroid/SealDownloader.java, EmojidexAndroid/src/main/java/com/emojidex/emojidexandroid/SealGenerator.java, EmojidexAndroid/src/main/java/com/emojidex/emojidexandroid/SendSealActivity.java, EmojidexAndroid/src/main/res/layout/dialog_sealkit.xml, EmojidexAndroid/src/main/res/values-ja/strings.xml, EmojidexAndroid/src/main/res/values/arrays.xml, EmojidexAndroid/src/main/res/values/strings.xml, EmojidexAndroidLibrary/src/main/java/com/emojidex/emojidexandroid/EmojidexFileUtils.java
- シールキットで長押しすると送信or保存の選択ダイアログを表示
- 背景を選択できるように変更
- 保存を選択するとローカルストレージに保存する
- 保存時にギャラリーに登録する
=> add save seal function
